---
- name: Build new Palo Alto EE using EE Utils collection
  hosts: "{{ target | default('builder_host') }}"
  become: true
  become_user: dpwuser450
  tags: buildee

  vars:
    ee_version: 3
    ee_builder_dir_clean: false
    ee_builder_dir: "/home/dpwuser450/ansible/builder/paloalto_ee" # Changed from /home/ansible due to permission denied
    ee_update_base_images: true
    
    # Base image and registry variables
    ee_base_image: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
    ee_base_sig_name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
    ee_container_policy: system
    ee_base_registry_username: "{{ rh_user | default(pah_user) }}"
    ee_base_registry_password: "{{ rh_pass | default(pah_pass) }}"
    
    ee_prune_images: true
    ee_pull_collections_from_hub: false
    alt_name: "Palo Alto Networks Execution Environment"
    ee_name: paloalto_ee
    ee_reg_credential: Automation Hub Container Registry
    ee_registry_dest: "{{ ah_host }}"
    ee_registry_username: "{{ pah_user }}"
    ee_registry_password: "{{ pah_pass }}"
    ee_verbosity: 1
    
    # Define the EE structure
    ee_list:
      - name: paloalto_ee
        alt_name: "Palo Alto Networks Execution Environment"
        tag: "{{ ansible_date_time.iso8601_basic_short }}"
        dependencies:
          python:
            # Install any required python packages directly
            - pan-os-python
            - pan-python
            - pandevice
            - xmltodict
            - requests
          galaxy:
            collections:
              - name: paloaltonetworks.panos
                version: ">=3.2.0"
              - name: community.general
          python_interpreter:
            python_path: "/usr/bin/python3.11"

  pre_tasks:
    - name: Login to PAH
      containers.podman.podman_login:
        username: "{{ pah_user }}"
        password: "{{ pah_pass }}"
        registry: "{{ ah_host }}"

    - name: Login to Red Hat Registry
      containers.podman.podman_login:
        username: "{{ rh_user | default(pah_user) }}"
        password: "{{ rh_pass | default(pah_pass) }}"
        registry: "registry.redhat.io"

  roles:
    # Ensure these roles exist in your controller environment
    - infra.ee_utilities.ee_builder

  post_tasks:
    - name: Update Execution Environment Version in Controller with new version
      ansible.controller.execution_environment:
        name: "{{ alt_name }}"
        image: "{{ ah_host }}/{{ ee_name }}:{{ ansible_date_time.iso8601_basic_short }}"
        credential: "{{ ee_reg_credential }}"
        controller_host: "https://{{ ah_host | regex_replace('^https?://', '') }}"
        validate_certs: false
      delegate_to: localhost
      become: false
