- name: Check Cisco IOS connections
  hosts: all
  gather_facts: no
 
  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
      register: facts

    - debug: var=facts.stdout_lines


 #   - debug: var=ansible_facts.keys()


