- name: Check Cisco IOS connections
  hosts: all
  ansible_connection: network_cli
  ansible_network_os: ios

  vars:
    cli:
      host: '{{ host }}'
      username: '{{ username }}'
      password: '{{ password }}'
  
  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
        provider: '{{ cli }}'
      register: facts

    - debug: var=facts.stdout_lines

