- name: Check Cisco IOS connections
  hosts: all
  collections:
    - cisco.ios
  tasks:
    - name: Gather facts
      ios_facts:
        provider: '{{ provider }}'
      register: facts

    - debug: var=facts.stdout_lines

