- name: Check Cisco IOS connections
  hosts: all
  collections:
    - cisco.ios
  vars:
    cli:
      host: “{{ inventory_hostname }}”
      username: cisco
      password: cisco
  
  tasks:
    - name: Gather facts
      ios_facts:
        provider: '{{ cli }}'
      register: facts

    - debug: var=facts.stdout_lines

