- name: Check Cisco IOS connections
  hosts: all
  gather_facts: no
 
  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
        host: '{{ host }}'
        username: '{{ username }}'
        password: '{{ password }}'
      register: facts

    - debug: var=facts.stdout_lines

 #   - debug: var=ansible_facts.keys()


