- name: Check Cisco IOS connections
  hosts: all
  collections:
    - cisco.ios
  vars:
    cli:
      host: '{{ host }}'
      username: '{{ username }}'
      password: '{{ password }}'
  
  tasks:
    - name: Gather facts
      ios_facts:
        provider: '{{ cli }}'
      register: facts

    - debug: var=facts.stdout_lines

