- name: Check Cisco IOS connections
  hosts: all

#  vars:
#    cli:
#      host: '{{ host }}'
#      username: '{{ username }}'
#      password: '{{ password }}'
  
  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
#        provider: '{{ cli }}'
      register: facts

    - debug: var=facts.stdout_lines


