- name: Check for free Cisco switch interfaces
  hosts: all
  gather_facts: false
   
  vars:
    output_path: "/home/ansiblereports/"
    filename: "free_interfaces_{{ date }}.csv"

  tasks:

    - name: CSV - Generate output filename
      set_fact: 
        date="{{lookup('pipe','date +%Y%m%d')}}"
      run_once: true

    - name: CSV - Create file and set the header
      lineinfile:
        dest: "{{ output_path }}/{{ filename }}"
        line: hostname,interface,description,lineprotocol,operstatus,accessvlan,voicevlan
        create: yes
        state: present
    - name: IOS Facts
      cisco.ios.ios_facts:
        gather_network_resources: l2_interfaces
        gather_subset: all
      register: fact
    
 #   - name: CSV - Get IOS devices facts
 #     set_fact:
 #       csv_tmp: >
 #         {{ fact[ansible_net_hostname] }},{{ fact[ansible_net_interfaces] }},{{ fact[ansible_net_interfaces[description]] }},{{ fact[ansible_net_interfaces[lineprotocol]] }},{{ fact[ansible_net_interfaces[operstatus]] }},{{ fact[ansible_net_hostname] }},{{ fact[ansible_net_hostname] }}

    - name: CSV - Write information into .csv file
      lineinfile:
        insertafter: EOF
        dest: "{{ output_path }}/{{ filename }}"
        line: "{{ fact.ansible_net_hostname] }},{{ item.key }},{{ item.value.description | default('') }},{{ item.lineprotocol }},{{ item.operstatus }},{{ item }},{{ item }}"
      loop: "{{ fact.ansible_net_interfaces | default({}) | dict2items }}"
      loop_control:
        loop_var: item
    - name: CSV - Blank lines removal
      lineinfile:
        path: "{{ output_path }}/{{ filename }}"
        state: absent
        regex: '^\s*$'