- name: Check for free Cisco switch interfaces
  hosts: all
  gather_facts: false
 
  tasks:
    - name: IOS Facts
      cisco.ios.ios_facts:
        gather_network_resources: l2_interfaces
        gather_subset: all
        register: iosfacts
    
    - name: Print facts
      debug:
        msg: {{iosfacts.stdout}}