- name: Capture show output
  hosts: all
  gather_facts: false
  connection: network_cli
   
  tasks:
    - name: show run
      ios_command:
        commands:
        - show version
        - show inventory
        - show run
        - show clock

        
        - show inter counters error
        - show inter counter
        - show int status
        - show int description
        - show int trunk
        - show spanning-tree summary
        - show spanning-tree root
        - show vlan brief
        - show mac address-table aging-time
        - show mac address-table dynamic

        - show ip arp

        - show ip int brief

        - show ip route summary
        - show ip route | i 00:0

        - show ip eigrp neighbors
        - show ip mroute summary

        - show logg

      register: config

    - name: show 2
      ios_command:
        commands:
        - show lldp neighbors
      ignore_errors: true
      register: config2

    - name: show 3
      ios_command:
        commands:
        - show ip cef
      ignore_errors: true
      register: config3

    - name: show 4
      ios_command:
        commands:
        - show fex
      ignore_errors: true
      register: config4

    - name: show 5
      ios_command:
        commands:
        - show port-chan summary
      ignore_errors: true
      register: config5

    - name: show 6
      ios_command:
        commands:
        - show ip int brief vrf all
      ignore_errors: true
      register: config6

    - name: show 7
      ios_command:
        commands:
        - show hsrp brief   
      ignore_errors: true
      register: config7

    - name: show 8
      ios_command:
        commands:
        - show cdp neighbors   
      ignore_errors: true
      register: config8
   
        
    - name: save output to local directory
      copy:
        content: "{{ config.stdout | replace('\\n', '\n') }}"
        dest: "/home/ansiblereports/show-output/{{ inventory_hostname }}.ios"

    - name: append new line EOF 2
      blockinfile:
        path: "/home/ansiblereports/show-output/{{ inventory_hostname }}.ios"
        insertafter: EOF
        block: "{{ config2.stdout | replace('\\n', '\n') }}"
      when: config2.stdout is defined

    - name: append new line EOF 3
      blockinfile:
        path: "/home/ansiblereports/show-output/{{ inventory_hostname }}.ios"
        insertafter: EOF
        block: "{{ config3.stdout | replace('\\n', '\n') }}"
      when: config3.stdout is defined

    - name: append new line EOF 4
      blockinfile:
        path: "/home/ansiblereports/show-output/{{ inventory_hostname }}.ios"
        insertafter: EOF
        block: "{{ config4.stdout | replace('\\n', '\n') }}"
      when: config4.stdout is defined

    - name: append new line EOF 5
      blockinfile:
        path: "/home/ansiblereports/show-output/{{ inventory_hostname }}.ios"
        insertafter: EOF
        block: "{{ config5.stdout | replace('\\n', '\n') }}"
      when: config5.stdout is defined

    - name: append new line EOF 6
      blockinfile:
        path: "/home/ansiblereports/show-output/{{ inventory_hostname }}.ios"
        insertafter: EOF
        block: "{{ config6.stdout | replace('\\n', '\n') }}"
      when: config6.stdout is defined

    - name: append new line EOF 7
      blockinfile:
        path: "/home/ansiblereports/show-output/{{ inventory_hostname }}.ios"
        insertafter: EOF
        block: "{{ config7.stdout | replace('\\n', '\n') }}"
      when: config7.stdout is defined

    - name: append new line EOF 8
      blockinfile:
        path: "/home/ansiblereports/show-output/{{ inventory_hostname }}.ios"
        insertafter: EOF
        block: "{{ config8.stdout | replace('\\n', '\n') }}"
      when: config8.stdout is defined