- hosts: all
  connection: local
  collections:
    - paloaltonetworks.panos
  tasks:
  - name: Apply "set session resource-limit-behavior bypass" command 
    panos_op:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'set session resource-limit-behavior bypass'
