- hosts: all
  connection: httpapi
  gather_facts: False
  collections:
    - paloaltonetworks.panos
  tasks:
  - name: Palo Alto set ctd pkt-proc-loop-low
    paloaltonetworks.panos.panos_op:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'set system setting ctd pkt-proc-loop-low 8190'
  - name: Palo Alto set ctd pkt-proc-loop-high
    paloaltonetworks.panos.panos_op:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'set system setting ctd pkt-proc-loop-high 8190'
    
