- hosts: '{{ target | default("firewall") }}'
  connection: httpapi
  gather_facts: False
  collections:
    - paloaltonetworks.panos
  tasks:
  - name: Palo Alto check
    paloaltonetworks.panos.panos_check:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      timeout: 15
  - name: Palo Alto set bypass
    paloaltonetworks.panos.panos_type_cmd:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'set'
      xpath: |
        /config/devices/entry[@name='localhost.localdomain']
        /deviceconfig/setting/tcp
      element: |
        <allow-challenge-ack>yes</allow-challenge-ack>
  - name: Palo Alto commit
    paloaltonetworks.panos.panos_commit:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'