- hosts: ha_pair
  connection: local
  collections:
    - paloaltonetworks.panos
  tasks:
  - name: Palo Alto check
    panos_check:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      timeout: 15
