- hosts: all
  connection: httpapi
  gather_facts: False
  collections:
    - paloaltonetworks.panos
  tasks:
  - name: Palo Alto Trusted zone
    paloaltonetworks.panos.panos_op:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'show zone-protection zone Trust'
  - name: Palo Alto DMZ zone
    paloaltonetworks.panos.panos_op:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'show zone-protection zone DMZ'