- hosts: all
  connection: httpapi
  gather_facts: False
  collections:
    - paloaltonetworks.panos
  tasks:
  - name: Palo Alto restart
    paloaltonetworks.panos.panos_restart:
      provider:
        username: '{{ username }}'
        password: '{{ password }}'
        ip_address: '{{ inventory_hostname }}'
