  collections:
    - paloaltonetworks.panos

- name: Palo Alto Sample
  hosts: all
  tasks:
  - name: Get the system info
    panos_op:
      provider: '{{ provider }}'
      cmd: 'show system info'
    register: res

  - debug:
      msg: '{{ res.stdout }}'
