- hosts: '{{ target | default("firewall") }}'
  connection: local
  collections:
    - paloaltonetworks.panos
  tasks:
  - name: Palo Alto check
    paloaltonetworks.panos.panos_check:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      timeout: 15
##