- hosts: all
  connection: local
  collections:
    - paloaltonetworks.panos
  tasks:
  - name: Palo Alto resource monitor
    panos_op:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'show running resource-monitor hour'
  - name: Palo Alto resource monitor day
    panos_op:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'show running resource-monitor day'