- hosts: fw_px_pa3220-1_mgt.ad.dpw.com

  tasks:
  - name: Palo Alto info
    paloaltonetworks.panos.panos_op:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'show system info'

- hosts: fw_px_pa3220-2_mgt.ad.dpw.com

  tasks:
  - name: Palo Alto info
    paloaltonetworks.panos.panos_op:
      username: '{{ username }}'
      password: '{{ password }}'
      ip_address: '{{ inventory_hostname }}'
      cmd: 'show system info'