- hosts: '{{ target | default("firewall") }}'
  connection: local
  tasks:
    - name: Palo Alto check
      paloaltonetworks.panos.panos_check:
        provider:
          username: '{{ username }}'
          password: '{{ password }}'
          ip_address: '{{ inventory_hostname }}'
        timeout: 15
##