- name: WiFi controller check
  hosts: all
  gather_facts: no
  tasks:
    - name: run datapath frame command
      raw: show datapath frame
      register: datapath
#    - name: send e-mail with info
#      hosts: 127.0.0.1
#      connection: local
#      mail:
#        host: outlook.dpw.com
#        port: 25
#        to: Networking <networking@davispolk.com>
#        subject: PY WiFi controller show datapath frame
#        body: '{{ datapath }}'
    - name: Send summary mail
      local_action:
        module: mail    
        host: outlook.dpw.com
        port: 25
        to: Networking <networking@davispolk.com>
        subject: PY WiFi controller show datapath frame
        body: '{{ datapath }}'
      run_once: True
