- name: WiFi controller reboot
  hosts: all
  gather_facts: no
  tasks:
    - name: run reload force
      raw: reload force
      register: datapath
#    - name: send e-mail with info
#      hosts: 127.0.0.1
#      connection: local
#      mail:
#        host: outlook.dpw.com
#        port: 25
#        to: Networking <networking@davispolk.com>
#        subject: PY WiFi controller show datapath frame
#        body: '{{ datapath }}'
    - name: Send summary mail
      local_action:
        module: mail    
        host: outlook.dpw.com
        port: 25
        from: ansible@davispolk.com
        to: networking@davispolk.com
        subject: PY WiFi controller reboot
#        body: '{{ datapath.stdout_lines }}'
        body: |
              {% for line in datapath.stdout_lines %}
                {{ line }}
                {% endfor %}
      run_once: True
