- name: WiFi controller check
  hosts: all
  gather_facts: no
  tasks:
    - raw: no paging
    - raw: show datapath utilization
      register: datapath2
    - raw: show port stats
      register: datapath3
    - raw: show acl hits
      register: datapath4
    - raw: show datapath frame
      register: datapath5
    - raw: show datapath frame all
      register: datapath6
    - raw: show datapath crypto counters
      register: datapath7
    - raw: show datapath debug opcode
      register: datapath8
    - raw: show datapath debug eth1info
      register: datapath9
    - name: Send summary mail
      local_action:
        module: mail    
        host: outlook.dpw.com
        port: 25
        from: ansible@davispolk.com
        to: honver.lam@davispolk.com
        subject:  'RE: 5363881161 - AOS - controller rebooted - ref:_00Dd0bUlK._5004oPFihQ:ref'
        body: |
              {% for line in datapath2.stdout_lines %}
                {{ line }}
                {% endfor %}
              {% for line in datapath3.stdout_lines %}
                {{ line }}
                {% endfor %}
              {% for line in datapath4.stdout_lines %}
                {{ line }}
                {% endfor %}
              {% for line in datapath5.stdout_lines %}
                {{ line }}
                {% endfor %}
              {% for line in datapath6.stdout_lines %}
                {{ line }}
                {% endfor %}
              {% for line in datapath7.stdout_lines %}
                {{ line }}
                {% endfor %}
              {% for line in datapath8.stdout_lines %}
                {{ line }}
                {% endfor %}
              {% for line in datapath9.stdout_lines %}
                {{ line }}
                {% endfor %}                                                                                                              
      run_once: True
