- name: WiFi controller check
  hosts: all
  gather_facts: no
  tasks:
    - name: run show version
      raw: show version
      register: version
    - name: Send summary mail
      local_action:
        module: mail    
        host: outlook.dpw.com
        port: 25
        from: ansible@davispolk.com
        to: networking@davispolk.com
        subject: WiFi controller show version
        body: |
              {% for line in version.stdout_lines %}
                {{ line }}
                {% endfor %}
      run_once: True
